### ISSUE TITLE
Xdebug not working

### ISSUE THREAD

**Issue by shuat** [markshust/docker-magento#177] opened 2019-08-16 20:22 UTC
I followed your instructions  and ran 
`bin/xdebug enable`

My launch.json looks like the below example
`https://github.com/markshust/docker-magento/blob/master/compose/magento-2/.vscode/launch.json`

Getting the following error in debug console

`Error applying xdebugSettings: invalid or missing options`

It is also not stopping on breakpoint .

**Comment by cernydav** [comment] 2019-08-20 07:51
Quick Fix: Remove xdebugSettings: { ... } from launch.json

**Comment by shuat** [comment] 2019-08-29 03:52
@cernydav Thanks for that suggestion as it removed the error. The issue is that even when running debug it does stop on breakpoints. What am I doing wrong?

**Comment by johan-lindahl** [comment] 2019-09-07 17:25
I had a similar problem and spent too much time trouble shooting. My problem was that my "Page Cache" was enabled.

System -> Cache Management

Select the "Page Cache" row in the Cache Type table and select "disable" in the drop down on the top to disable the "Page Cache".

After I disabled the "Page Cache" everything was working as intended.

**Comment by markshust** [comment] 2019-09-13 13:50
closing this one out, as it appears to be working for other people. @shuat  i'm only intricately familiar with phpstorm, but perhaps someone can help you with this.

**Closed by markshust** 2019-09-13 13:50 UTC
