### ISSUE TITLE
continuous problem with permissions

### ISSUE THREAD

**Issue by albertobraschi** [markshust/docker-magento#229] opened 2020-02-24 21:57 UTC
**Description**
continuous problem with permissions

**Steps To Reproduce**
1. bin/n98-magerun2 setup:config:set --page-cache=redis --page-cache-redis-server=redis --page-cache-redis-db=1

**Expected Result**
configure redis

**Actual Result**
 bin/n98-magerun2 setup:config:set --page-cache=redis --page-cache-redis-server=redis --page-cache-redis-db=1
Overwrite the existing configuration for db-ssl-verify?[Y/n]y
Overwrite the existing configuration for page-cache?[Y/n]y
Overwrite the existing configuration for page-cache-redis-server?[Y/n]y
Overwrite the existing configuration for page-cache-redis-db?[Y/n]y

In ConfigModel.php line 166:                                                     
  Missing write permissions to the following paths:  
  /var/www/html/app/etc                              

Other                                                    

**Steps To Reproduce**
1.  bin/magento sampledata:deploy

**Expected Result**
install sample data

**Actual Result**
./composer.json is not writable.
There is an error during sample data deployment. Composer file will be reverted.

**Comment by rangerz** [comment] 2020-04-23 05:10
@albertobraschi, I can't reproduce this behavior. This seems to be a file permission issue. Try to `bin/restart` them and run `bin/fixowns` and `bin/fixperms`

Follow these full commands
```
bin/restart
bin/fixowns
bin/fixperms

# Double check the permissions
bin/cli ls -l ./composer.json
# -rw-r--r-- 1 app app 3588 Apr 23 03:56 ./composer.json

bin/cli ls -al ./app/etc/env.php
# -rw-rw-r-- 1 app app 3727 Apr 23 05:02 ./app/etc/env.php

# They should be writable for app owner.
```

**Comment by markshust** [comment] 2020-05-12 20:19
I'm closing, as I can't reproduce either. Please try re-running the setup/install process and try again. The helper scripts by @rangerz should be helpful to correct any perm or ownership issues which may come up.

**Closed by markshust** 2020-05-12 20:19 UTC
Labels: unable to replicate
