### ISSUE TITLE
cannot access 'bin/magento': No such file or directory (Mac M1 chip)

### ISSUE THREAD

**Issue by RicardoDiezTroquer** [markshust/docker-magento#518] opened 2021-08-19 21:28 UTC
**Description**
Hello everyone, I hope you are well, I am writing here to see if you can help me with a problem that I have had for several days. I am trying to create a new magento 2 project following the manual setup steps and it always returns this error message in step 4 "/ bin / chmod: cannot access 'bin / magento': No such file or directory", they have idea of what is due? I leave the information about my environment.

Docker 3.3.3
Mac mini (M1, 2020) Memory 16GB
SO : macOS Big Sur 11.5.2

**Steps To Reproduce**
1. following the manual configuration steps in the fourth step I run this command "bin / setup magento.test"

**Expected Result**

**Actual Result**
"/ bin / chmod: cannot access 'bin / magento': No such file or directory"
![Captura de Pantalla 2021-08-19 a la(s) 16 28 20](https://user-images.githubusercontent.com/89224713/130146723-2c565427-b770-4b99-a27c-ced82a3b5871.png)

**Comment by jasonloeve** [comment] 2021-08-24 08:59
Looks like something with the installer not allowing full download of Magento ? You may have to do an initial Magento download using composer so you can manually authenticate using the access key you create in your Magento account.

`composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`

Then follow the **Existing Projects** instructions.

Busy trying this route now to see if it works.

**Comment by markshust** [comment] 2021-08-31 14:22
Going to close this out as a dupe of https://github.com/markshust/docker-magento/issues/396

**Closed by markshust** 2021-08-31 14:22 UTC
Labels: duplicate

**Comment by kd-labs** [comment] 2021-12-21 10:24
Hi Guys,

I'm getting the same issue, as shown in the logs below,

I'm running the onelinesetup on Windows10. Could someone guide me on what to do here.

```shell
Starting magento_redis_1 ...
Starting magento_phpfpm_1 ...
Starting magento_mailcatcher_1 ...
Starting magento_rabbitmq_1    ...
Starting magento_app_1         ...
Starting magento_elasticsearch_1 ...
Starting magento_mailcatcher_1   ... done
Starting magento_phpfpm_1        ... done
Starting magento_redis_1         ... done
Starting magento_rabbitmq_1      ... done
Starting magento_db_1            ... done
Starting magento_elasticsearch_1 ... done
Starting magento_app_1           ... done
chmod: cannot access 'bin/magento': No such file or directory

```

**Comment by markshust** [comment] 2021-12-21 17:58
@kd-labs your install must have failed. I'd recommend removing your entire project with `bin/removeall`, remove the project directory, and attempting the install again.

**Comment by mgonzalezurbano** [comment] 2022-02-17 15:24
I got the same error , my installation got interrupted without any error. So I print $? and got error code 137. It means no enough memory therefore I increased the memory of my Linux host and it worked :)

**Comment by luki1oo1** [comment] 2023-11-08 15:55
![image](https://github.com/markshust/docker-magento/assets/34570907/92750dfe-9e07-4a08-8e30-fc50c84693f5)
Also, I have a problem, does anyone have an idea how to solve it?

**Comment by ajahongir** [comment] 2024-02-15 19:05
having same issue. removing project and making it again - dont helping.
