### ISSUE TITLE
Unable to get SSL Certificate

### ISSUE THREAD

**Issue by draper87** [markshust/docker-magento#504] opened 2021-08-04 15:47 UTC
**Description**
During setup with
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2`
I got this notification:

> Generating SSL certificate...
> cat: can't open '/root/.local/share/mkcert/rootCA.pem': No such file or directory
> Created a new local CA at "/root/.local/share/mkcert" 💥
> The local CA is now installed in the system trust store! ⚡️
> 
> System password requested to install certificate authority on host...
> Updating certificates in /etc/ssl/certs...
> 0 added, 0 removed; done.
> Running hooks in /etc/ca-certificates/update.d...
> done.
> Using the local CA at "/root/.local/share/mkcert" ✨
> 
> Created a new certificate valid for the following names 📜
>  - "magento.test"
> 
> The certificate is at "nginx.crt" and the key at "nginx.key" ✅

After checking with Chrome on Ubuntu 18.04 the SSL certificate looks invalid as shown here below
![Screenshot from 2021-08-04 17-42-04](https://user-images.githubusercontent.com/61914749/128211268-d76890ca-4bcf-4a7d-8654-9f1380256bd1.png)

![Screenshot from 2021-08-04 17-43-08](https://user-images.githubusercontent.com/61914749/128211636-d5d32657-71e2-4e5c-93c3-b8f0619b1f33.png)

What should I do in order to solve this issue?
**Steps To Reproduce**
1. `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.2`

**Expected Result**
A valid certificate

**Actual Result**
Invalid certificate

**Comment by nverhoye** [comment] 2021-08-04 19:48
Hello,

Same issue here.

**Comment by markshust** [comment] 2021-08-06 03:06
This appears to be a duplicate of https://github.com/markshust/docker-magento/issues/222

**Closed by markshust** 2021-08-06 03:06 UTC

**Comment by Axel29** [comment] 2022-05-26 11:52
Hi,

I've just set up an existing project with your docker for the first time and I also get an `NET::ERR_CERT_AUTHORITY_INVALID` error.

I tried running the following commands: `bin/setup-ssl thesages.test` and `bin/setup-ssl-ca thesages.test`, which didn't thrown any error, but still the SSL is invalid.

I'm using Ubuntu 21.10 and the latest version of your Docker environment.

Thanks for your help.

**Comment by markshust** [comment] 2022-05-27 02:06
That's odd, because the contents of that comment should be the exact same file as the root `bin/setup-ssl-ca` script at https://github.com/markshust/docker-magento/blob/master/compose/bin/setup-ssl-ca as I merged in the related PR.

I'm honestly not sure was I don't currently have an Ubuntu machine set up to test this all out.

**Comment by AngeloZou** [comment] 2023-07-15 16:53
I'm using ubuntu 22.04, and I had the same problem.
https://github.com/markshust/docker-magento/discussions/959

**Comment by postadelmaga** [comment] 2024-08-05 16:05
I got the same issue on Arch Linux, apparently the `bin/setup-ssl-ca` is not 100% compatible with Arch: for some reason it needs `dpkg` and `libnss3-tools`

`Successfully copied 3.58kB to /home/soham/Sites/magento/.
System password requested to install certificate authority on host...
bin/setup-ssl-ca: riga 41: dpkg-query: not found
`
So I installed `dpkg` but a re-run `bin/setup-ssl-ca` but then I got:
`dpkg-query: missing package libnss3-tools`
