### ISSUE TITLE
Compatibility with Apple's ARM M1-chip

### ISSUE THREAD

**Issue by nayembwip** [markshust/docker-magento#531] opened 2021-09-18 19:46 UTC
Getting "no matching manifest for linux/arm64/v8 in the manifest list entries" when trying to run quick setup command. Getting this error around "db Pulling". Seems like it's not working for new Mac with M1 chip. 

<img width="565" alt="Screenshot 2021-09-19 at 1 45 34 AM" src="https://user-images.githubusercontent.com/73821752/133906821-dcfbd68f-ea2e-464a-a7e8-83405a0ababf.png">

**Comment by markshust** [comment] 2021-09-21 15:41
Closing this out as a duplicate of https://github.com/markshust/docker-magento/issues/396

**Closed by markshust** 2021-09-21 15:41 UTC
