### ISSUE TITLE
Add (s)FTP support to image

### ISSUE THREAD

**Issue by Krielkip** [markshust/docker-magento#344] opened 2020-11-09 13:54 UTC
**Description**
The wish is to add (s)Ftp support to the docker, to upload the files towards the docker image, instead of mirroring. 
With Dockware (Shopware) this has some performance wins towards the cached way of syncing.

**Comment by markshust** [comment] 2020-11-10 14:36
Hi @Krielkip, can you explain exactly what you are trying to do? Any FTP'ing/uploading will definitely be slower than syncing them with something like rsync or docker cp.

**Comment by Krielkip** [comment] 2020-11-10 15:34
@markshust sure 😄 

At this moment we are developing with Mac and PhpStorm. Because of the sync (cached / delegation) the Docker setup really slow compaired to the Linux coworkers. 

For Shopware we are using Dockware. (https://dockware.io/docs#start-developing) 
Which uses at start of setup docker cp. 
When you code the IDE (PhpStorm) uses the SFtp auto upload to ftp it to the docker.

This is for on the fly development and not for the whole upload . For example in the docks: "https://dockware.io/docs#persisting-data" And more info about "slow upload" a little bit above.

With this we don't need to "sync" the whole app folder like now and we could have a speed boost. 
Thanks in advance.

**Comment by markshust** [comment] 2020-11-10 15:48
Yea, I've went through all of the folder/filesystem already with performance https://markshust.com/2018/12/30/docker-mac-filesystem-volume-mount-approach-performance/

I do an initial docker cp, then selective sync what folders to mount. This project does not mount all folders. I think this will fallback to PHPStorm support of Docker and remote filesystems.

**Comment by Krielkip** [comment] 2020-11-17 09:05
Hello @markshust,

Sorry for adding a reply. 
For us it would be a winner if we can have a sFTP in the container, to only upload changed files by the IDE, instead of mount a couple of folders. 

Today i run some tests and it is winning 200ms on a "basic" setup. 
With app/design & app/code mounted
![Schermafbeelding 2020-11-17 om 09 53 07](https://user-images.githubusercontent.com/10194846/99367869-c8a1b100-28ba-11eb-9335-b1d96a912077.png)
LightHouse: 
![Schermafbeelding 2020-11-17 om 09 55 14](https://user-images.githubusercontent.com/10194846/99368307-42399f00-28bb-11eb-93c4-be57cdab7d5c.png)


Without mounted:
![Schermafbeelding 2020-11-17 om 09 53 27](https://user-images.githubusercontent.com/10194846/99367935-dbb48100-28ba-11eb-8fa8-ff16905a205b.png)
LightHouse: 
![Schermafbeelding 2020-11-17 om 09 54 42](https://user-images.githubusercontent.com/10194846/99368276-3948cd80-28bb-11eb-880f-1f46bce37346.png)


Network loading Lighthouse;
Left: No Mount / Sync;  [ Ready in 7668 MS ] 
Right: Sync (app/code, app/design) [ Ready in 19268 MS ]
![Schermafbeelding 2020-11-17 om 09 55 57](https://user-images.githubusercontent.com/10194846/99368388-5f6e6d80-28bb-11eb-8d91-d6c37ecb3ec9.png)

Difference of +/ 12.000 ms; on our side. 
It would be great if you can add sFTP, without changing for all other users 💯

**Comment by markshust** [comment] 2020-11-19 14:39
Hi @Krielkip, thanks much for the perf reports, I reopened the ticket. Do you have instructions for setting up PHPStorm with this SFTP setup? If so, I can test this locally and will definitely merge in if we can get this working as desired.

**Comment by Krielkip** [comment] 2020-12-01 13:54
Sorry for my late response. 

I have used the example of this project:
https://dockware.io/assets/docs/img/sftp-connection.png

Useraccount & password can be magento :) 

More information : https://www.jetbrains.com/help/phpstorm/uploading-and-downloading-files.html

**Comment by markshust** [comment] 2020-12-03 14:06
@Krielkip no worries, I mute GitHub notifications now so only on here once a week anyways. Thank you for the info, I will look into this.

**Comment by markshust** [comment] 2020-12-05 15:51
@Krielkip I think I'll need some additional input/debugging from you.

I created a new Docker image for SSH, creating a `Dockerfile` with the contents:

```
FROM debian:buster-slim

RUN apt-get update && apt-get install -y ssh

RUN groupadd -g 1000 app \
 && useradd -g 1000 -u 1000 -d /var/www -s /bin/bash app

RUN echo 'app:app' | chpasswd

RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
```

Then build it with: `docker build -t markoshust/ssh`. This creates an SSH server with a username & password both being `app`.

Then, add these lines to the `docker-compose.dev.yml` file:

```
  ...
  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"
```

Then after running `bin/start`, you'll have the SSH server running. I have verified this by connecting to it with PHPStorm:

<img width="1244" alt="Screen Shot 2020-12-05 at 10 46 23 AM" src="https://user-images.githubusercontent.com/437029/101247384-5c5ee400-36e7-11eb-8f76-84a9ff520018.png">

<img width="1800" alt="Screen Shot 2020-12-05 at 10 47 42 AM" src="https://user-images.githubusercontent.com/437029/101247389-62ed5b80-36e7-11eb-9804-28fdf4847489.png">

<img width="1800" alt="Screen Shot 2020-12-05 at 10 47 48 AM" src="https://user-images.githubusercontent.com/437029/101247396-6bde2d00-36e7-11eb-9c34-36964f507d63.png">

<img width="410" alt="Screen Shot 2020-12-05 at 10 46 30 AM" src="https://user-images.githubusercontent.com/437029/101247401-713b7780-36e7-11eb-956b-3c08ff5a13c3.png">

However, when I right click on a file, then go to Deployment > Upload to server:

<img width="1209" alt="Screen Shot 2020-12-05 at 10 49 11 AM" src="https://user-images.githubusercontent.com/437029/101247427-9def8f00-36e7-11eb-80ec-9bddc54407a4.png">

I get a "[12/5/20, 10:49 AM] Upload to m241.test failed: could not list the contents of folder "sftp://localhost/". (No such file)" error:

<img width="1920" alt="Screen Shot 2020-12-05 at 10 49 27 AM" src="https://user-images.githubusercontent.com/437029/101247431-a647ca00-36e7-11eb-9c89-bfcdb2ac2b85.png">

I'm using the instructions at https://www.jetbrains.com/help/phpstorm/uploading-and-downloading-files.html#551d8

I think we are so close, but I'm not sure why it's not receiving the directory contents. Any help would be appreciated.

**Comment by markshust** [comment] 2020-12-05 15:54
Ah, it may be because I didn't prime the entire filesystem on the container. Let me try a completely new install with everything residing on the container volume and retest.

**Comment by Krielkip** [comment] 2020-12-07 08:55
Yes i think you are missing the volumes :) 
It will try it also with your instructions. 


```
  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"
    volumes: *appvolumes
```

**Comment by Krielkip** [comment] 2020-12-13 15:50
Hello @markshust ,

I have tested it with your post. 
My docker-compose.yml; 

```
services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
      - ssh
  ... 
  ssh:
    image: markoshust/ssh
    ports:
      - "22:22"
    volumes: *appvolumes
...
```

so i have edited: add your ssh image;
Added Volumes to your code
And i did link the ssh to the nginx container. 

My Remote Browser in PHPStorm;
<img width="490" alt="Schermafbeelding 2020-12-13 om 16 44 02" src="https://user-images.githubusercontent.com/10194846/102016705-7db47580-3d62-11eb-9fbb-0b8e27f594b7.png">

And trial remote upload:
<img width="774" alt="Schermafbeelding 2020-12-13 om 16 49 49" src="https://user-images.githubusercontent.com/10194846/102016826-3ed2ef80-3d63-11eb-926c-fc496e4adc43.png">

**Comment by Krielkip** [comment] 2020-12-18 14:25
I forgot; 
This is my docker-compose.dev.yml

```
version: "3"
services:
  app:
    volumes: &appvolumes
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached

  phpfpm:
    volumes: *appvolumes

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"
```

Maybe will update the nginx.conf.sample as copy on the server another optimalisation.

**Comment by joaolisboa** [comment] 2022-03-25 18:48
I have done all this and everything seems to be working, but for some reason seconds after saving a file it's just completely emptied in the remote and then on the host. Does anyone know any reason for this to happen? I'm really struggling to figure out what exactly is happening.

**Comment by markshust** [comment] 2022-03-27 20:03
@joaolisboa I believe this is a really old ticket that was never closed.

Have you seen https://github.com/markshust/docker-magento/#ssh? If possible, can you try those instructions and see if it works better than anything defined in this ticket? Once confirmed I can close this one out.

**Comment by Krielkip** [comment] 2022-03-28 10:20
> I have done all this and everything seems to be working, but for some reason seconds after saving a file it's just completely emptied in the remote and then on the host. Does anyone know any reason for this to happen? I'm really struggling to figure out what exactly is happening.

This looks like some files are stil being synced on your Docker. 
This ticket is rather old, as markshust said. 
--- 

in 2021 i have used the SSH of this ticket a lot. So the solution worked 👍  
Need to find my 2021 files and share the yml i used. But then again. This project has been updated.

**Comment by markshust** [comment] 2022-03-28 14:32
Thanks. I'm going to close this out, but if you are still having issues feel free to leave another comment 👍

**Closed by markshust** 2022-03-28 14:32 UTC
