### ISSUE TITLE
Can't import the db

### ISSUE THREAD

**Issue by linetsoscar** [markshust/docker-magento#608] opened 2022-01-03 21:16 UTC
Helo i have a problem by importing a database from another project, the issue is like this:
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Downloading n98-magerun2.phar, just a moment...
n98-magerun2.phar: OK

I folowed just exactly how you just did in one of your videos with:
bin/mysql -uroot -pmagento < magento.sql 

and not working... just in case im extracting the database from a magento default project downloaded and its not even working.
Need help, thankls!

**Comment by nexen2C** [comment] 2022-01-05 16:02
can you try this one @linetsoscar 
bin/mysql <  magento.sql

**Comment by markshust** [comment] 2022-01-10 17:52
It looks like no matter what command you try to use, the error will still occur. You'll want to check your backup SQL file to ensure it is in the correct format, as line 1 is erroring out for you. An online SQL checker may help you out. But, this is not a bug with this project, so I'll be closing this ticket out. Feel free to open a Discussion at https://github.com/markshust/docker-magento/discussions if you need more assistance.

**Closed by markshust** 2022-01-10 17:52 UTC
