### ISSUE TITLE
Sample data not install on 2.4.7

### ISSUE THREAD

**Issue by sachin1830** [markshust/docker-magento#1180] opened 2024-06-26 16:41 UTC
**Description**
By following this tutorial I did the local setup which is working fine but when I run the "bin/magento sampledata:deploy" in this case i did not get an error but my sample did not install 

**Steps To Reproduce**
1. run "bin/magento sampledata:deploy" on project root 

<img width="1463" alt="Screenshot 2024-06-26 at 10 05 29 PM" src="https://github.com/markshust/docker-magento/assets/46964628/d946b008-50fe-48c9-939a-133c58213b36">

run : bin/magento setup:upgrade

**Expected Result**
sample data should install

**Actual Result**
sample data not installed

**Comment by YevhenZvieriev** [comment] 2024-06-26 20:12
Hi, @sachin1830 

Have you executed the `bin/magento set:up` after installing sample data?

**Comment by sachin1830** [comment] 2024-06-27 15:08
yes I have executed bin/magento set:up after installing sample data

**Comment by YevhenZvieriev** [comment] 2024-06-27 20:38
Try to execute these commands:

```
bin/magento set:up

bin/magento set:di:comp

bin/magento setup:static-content:dep -f
```

**Comment by sachin1830** [comment] 2024-06-29 09:30
hi @YevhenZvieriev i have already run these commands as well

**Comment by YevhenZvieriev** [comment] 2024-06-29 11:24
Ensure that the Magento file system permissions are correctly set. Incorrect permissions can cause issues with the deployment of sample data.

```
bin/fixowns

bin/fixperms
```

Check the Magento log files and verify that the sample data tables are created in the database. If not, there might be an issue with the database connection or permissions.

I can't reproduce this issue, in my case, everything works fine.

**Comment by sachin1830** [comment] 2024-07-03 16:32
Hi @YevhenZvieriev I ran the above 2 commands for permission and checked my Magento logs and I am getting it as well.

I tried creating a product manually and saving it. It works fine for me, But the sample data deploy not working.

**Comment by YevhenZvieriev** [comment] 2024-07-03 19:03
Hi, @sachin1830 

Given the persistent issues with deploying sample data, it might be more efficient to reinstall Magento.

Sometimes starting fresh can resolve underlying issues that are difficult to pinpoint. Starting with a clean installation can often resolve issues more quickly than troubleshooting complex problems. Please give this a try and let me know how it goes.

**Comment by bhushanmeetanshi** [comment] 2024-07-09 11:22
@sachin1830 Manual Docker setup guide line provided by @markshust is good enough for me. 

Kindly execute commands step by step as per given instruction and reinstall it as commented by @YevhenZvieriev.

**Comment by markshust** [comment] 2024-07-09 19:36
I cannot replicate this, so closing it out.

**Closed by markshust** 2024-07-09 19:36 UTC
