### ISSUE TITLE
Can't install docker-magento on M1 pro

### ISSUE THREAD

**Issue by shaikafrin05** [markshust/docker-magento#728] opened 2022-07-06 00:10 UTC
**Description**
Getting the below error when installing new project/manual setup/existing project
 chmod: cannot access 'bin/magento': No such file or directory

**Steps To Reproduce**
1. Install docker desktop on M1 pro(apple chip)
2. Created Sites/magento
3. Run onelinesetup command or manual setup commands or existing project commands. (curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.4
)
4. 

**Expected Result**
Installation should be successful.

**Actual Result**
Couldn't complete the installation and getting the error
chmod: cannot access 'bin/magento': No such file or directory
<img width="948" alt="Screen Shot 2022-07-05 at 6 09 18 PM" src="https://user-images.githubusercontent.com/102389812/177436507-1b9ee319-31f6-49f6-b391-7f22cb9145b3.png">

**Comment by piontuso** [comment] 2022-07-06 07:29
you can use temporary workaround like below:
1. `docker exec -it magento_phpfpm_1 bash`
2. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.3 .`
3. `exit`
4. `bin/setup magento.test`

**Comment by markshust** [comment] 2022-07-20 11:19
I'm unable to replicate this on an M1 Max chip, everything installs fine. That said, closing this as it seems to be a dupe of https://github.com/markshust/docker-magento/issues/731

**Closed by markshust** 2022-07-20 11:19 UTC
