### ISSUE TITLE
Xdedug doesnt work

### ISSUE THREAD

**Issue by boris1988** [markshust/docker-magento#797] opened 2022-10-23 20:27 UTC
**Description**
Xdebug doesn't work me
Ubuntu 20.20, Phpstorm 2022.2
I implemented all steps from the readme
I have a breakpoint in pub/index.php

did you have similar issues before?

**Steps To Reproduce**
![Screenshot from 2022-10-23 23-21-13](https://user-images.githubusercontent.com/2422927/197416399-c8c8d064-1791-4dfd-962d-ae9430bab7ee.png)
![Screenshot from 2022-10-23 23-21-41](https://user-images.githubusercontent.com/2422927/197416451-383c93ec-cfa6-40a5-a6a1-6209f97f988e.png)
![Screenshot from 2022-10-23 23-23-21](https://user-images.githubusercontent.com/2422927/197416476-ea05764a-6cc5-4848-a82e-135e65c7e92d.png)
![Screenshot from 2022-10-23 23-23-45](https://user-images.githubusercontent.com/2422927/197416504-9cb405da-92f1-417f-9292-598b6b84c1c0.png)
![Screenshot from 2022-10-23 23-24-54](https://user-images.githubusercontent.com/2422927/197416523-5fb10b64-96f5-4dcc-92c5-14616825255a.png)
![Screenshot from 2022-10-23 23-25-31](https://user-images.githubusercontent.com/2422927/197416548-74a47b66-02cf-4fec-922d-f74a68963d0b.png)

**Expected Result**
Xdebug works

**Actual Result**
Xdebug doenst works

**Comment by boris1988** [comment] 2022-10-23 20:31
Have found some messages:


⚠️ | [Step Debug] Creating socket for 'host.docker.internal:9003', getaddrinfo: Invalid argument. | 🖹
-- | -- | --
🛑 | [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(

**Comment by boris1988** [comment] 2022-10-23 20:48
My PhpStorm using Port 9003
tcp6       0      0 :::9003                 :::*                    LISTEN      104015/java

**Comment by boris1988** [comment] 2022-10-23 21:15
cannot solve it

**Comment by markshust** [comment] 2022-10-24 17:30
I'm not on Ubuntu/linux, but will leave this open in the hopes that someone else can help you fix this.

**Comment by rogerdz** [comment] 2022-10-25 16:24
You can try add this for php service in docker-compose.yml: 
extra_hosts: 
     - "host.docker.internal:host-gateway"

**Comment by markosege** [comment] 2022-10-28 14:05
I have the same problem but when i check php -v i don't see xdebug normally i see the xdebug version

@rogerdz @markshust @eltonmota

**Comment by markosege** [comment] 2022-10-28 15:14
@rogerdz  Thanks and your solution works for me

**Comment by eltonmota** [comment] 2022-10-28 15:47
Hello @markosege how do you made? Do you use linux ubuntu?

Thanks!

**Comment by markosege** [comment] 2022-10-28 15:56
@eltonmota yes I have ubuntu and see below what I did
`  phpfpm:
    image: markoshust/magento-php:7.4-fpm-15
    volumes: *appvolumes
    env_file: env/phpfpm.env
    #extra_hosts: *appextrahosts
    extra_hosts:
      - "host.docker.internal:host-gateway"`

**Comment by markosege** [comment] 2022-11-07 14:08
Hello @rogerdz your solution works on php 7.4, not php 8.1

**Comment by markosege** [comment] 2022-11-07 16:21
I have PHP 7.4 image and PHP 8.1 image, but xdebug only works on 7.4 bothe have same configuration on phpstorm

**Comment by cristiro7** [comment] 2022-11-16 10:05
Hi @markosege , I have the same with you with php 8.1.
I am trying to follow these step and now it work for me : 
- 1. Add  "host.docker.internal:172.17.0.1" to app.extra_hosts in docker-compose.yml (see https://github.com/markshust/docker-magento#the-hostdockerinternal-hostname) => Then start all containers by **bin/restart**
- 2. Open port 9003 on the firewall **docker run --rm alpine ip route | awk 'NR==1 {print $3}'** , (see https://github.com/markshust/docker-magento#extra-settings)
- 3. Enable xdebug **bin/xdebug enable**

Let try and verify again.

**Comment by markosege** [comment] 2022-11-16 15:27
@cristiro7 I tried and still have the same problem I am using ubuntu 20.04. even with PHP 7.4 on ubuntu 20.04. if you don't mind can you please share your "docker-compose.yml" where you make the changes. With popos, PHP 7.4 was working and not work with ubuntu 20.04

**Comment by cristiro7** [comment] 2022-11-17 02:38
@markosege, I'm using ubuntu 21.10, but I think it's not relates. this is my "docker-compose.yml"
https://drive.google.com/file/d/12395esFPQ9oGB1vvQQGHJqDNvRRe4sdO/view?usp=sharing

Please make sure that you opened port and enable xdebug.

**Comment by markosege** [comment] 2022-11-18 16:09
@cristiro7 I did the same except using PHP7.4 and not working see my "docker-compose.yml" attached

also, open port 9003 
[docker-compose.zip](https://github.com/markshust/docker-magento/files/10042886/docker-compose.zip)

**Comment by markosege** [comment] 2022-11-28 22:09
@cristiro7 also when i run this command `bin/cli cat /usr/local/etc/php/php.ini` out put is below

```
memory_limit = 4G
max_execution_time = 1800
zlib.output_compression = On
cgi.fix_pathinfo = 0
date.timezone = UTC

xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.idekey = PHPSTORM

upload_max_filesize = 100M
post_max_size = 100M
max_input_vars = 10000

sendmail_path = "/usr/bin/msmtp -t"
```

**Comment by asannikov** [comment] 2022-12-01 21:48
Have the same issue on mac

**Comment by markosege** [comment] 2022-12-05 14:13
@andy-sixtystores i change like yours but still not working for me not sure where is the issue

**Comment by salesigniter** [comment] 2022-12-06 01:34
I just wanted to add I tried all these steps and it wasn't that, it's something easier.  I used default everything (no changes to host name in php.ini) you just need to add this to your nginx.conf.sample with the name of your server, phpstorm requires that for xdebug to work

`server_name  magento.test;`

issue: https://github.com/markshust/docker-magento/issues/825

**Comment by markosege** [comment] 2022-12-06 14:54
@salesigniter I have the same config for Linux but not working


![phpstormxdebug](https://user-images.githubusercontent.com/20807820/205945268-132cd1d3-668d-4cde-9edb-10bf08f57b4a.png)

**Comment by salesigniter** [comment] 2022-12-07 09:58
@markosege did you add this to your nginx.conf.sample and restart your container? 

![image](https://user-images.githubusercontent.com/321250/206146691-09cd63ad-9c71-4118-837d-2bfc6e676a8a.png)

@markshust I want to recommend if possible the server_name being automatically added when the docker-magento is first run you add automatically the server_name to the nginx.conf.sample, the default or whatever server name is chosen: 

`server_name magento.test;`

**Comment by markosege** [comment] 2022-12-07 15:12
@salesigniter if I add server name to nginx.conf.sample it will automatically new one to the PHP storm config section. I think it's kind of the same server name as nginx.conf.sample or PHP storm config

my issue is resolved with @andy-sixtystores method and I update xdebug configuration chrome extension like below
![image](https://user-images.githubusercontent.com/20807820/206216468-78cb1fd9-75ed-4a82-8f87-3fb350039f21.png)

**Comment by markshust** [comment] 2022-12-28 12:52
I added the reference to the `compose.yaml` file in a comment. This is only applicable to linux it seems. If it is incorrect, please let me know, but it appears to be working after this is added from the comments above.

**Closed by markshust** 2022-12-28 12:52 UTC
Labels: help wanted, question

**Comment by giangvdm** [comment] 2023-05-13 09:37
> OK, I have mine working now with VSCode after a lot of trial and error.
> 
> I updated `compose.yaml` in a couple of places.
> 
> For the `app` service I added the following:
> 
> ```
>     extra_hosts: &appextrahosts
>       ## Selenium support, replace "magento.test" with URL of your site
>       #- "magento.test:172.17.0.1"
>       - "host.docker.internal:host-gateway"      
> ```
> 
> and for the `phpfpm` service I added the following:
> 
> ```
>     extra_hosts: *appextrahosts
> ```

I can confirm this solution works for me. Been fiddling around but nothing worked, then this one worked right on the first time! Thanks a bunch!
