### ISSUE TITLE
app-1 can't be binded to port 80 and 443 on Arch-based linux

### ISSUE THREAD

**Issue by memory-hunter** [markshust/docker-magento#971] opened 2023-08-04 11:02 UTC
OS: EndavourOS Nova 2023-03

**Description**

When running the `bin/download`, or any command that relaunches the containers, app-1 container, which is written to run on 80 and 443 in `compose.yaml`. That doesn't go well in Linux.

**Steps To Reproduce**
1. Simply run the one line install code snippet or follow manual installation until `bin/setup` (not including)

**Expected Result**
Magento should install into an empty project and should be able to access `magento.test`

**Actual Result**
Fails with error:

```
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: permission denied
```

**Workarounds**
1. I tried `sudo sysctl net.ipv4.ip_unprivileged_port_start=0`, which makes ports starting from 0 unprivileged. As per default, 0-1024 ports are privileged. This, I assume, is an unsafe "hack". With this, the setup runs but then when entering `magento.test`, I get a security warning.

2. In `compose.yaml`, write different porst to app-1. This doesn't work in the end since `magento.test` can't be accessed.

**Comment by memory-hunter** [comment] 2023-08-15 10:44
#972 references the same problem

**Comment by markshust** [comment] 2023-08-25 19:41
Dupe of https://github.com/markshust/docker-magento/issues/972

**Closed by markshust** 2023-08-25 19:41 UTC

**Comment by memory-hunter** [comment] 2023-08-25 19:52
@markshust wait.. isn't it supposed to work the other way around? #972 is a duplicate of mine, i posted earlier 🤣

**Comment by markshust** [comment] 2023-08-25 20:07
Eh probably... I think they are both closed. It's been a long week, hah 🙃

**Comment by memory-hunter** [comment] 2023-08-25 20:11
> Eh probably... I think they are both closed. It's been a long week, hah 🙃

It's okay, I get it :P the other one is open still
