### ISSUE TITLE
After setup markshust/docker-magento, local projects are not working

### ISSUE THREAD

**Issue by Mage2developer** [markshust/docker-magento#743] opened 2022-07-26 07:21 UTC
**Description:**

I have followed the steps to install and set up a new project from **Automated Setup (New Project)**, and the project setup was done successfully with sample data. After that to run my local projects I tried to open my local URL(http://local.ce243.com/), the url not working and gives the following error:
![not-working-project](https://user-images.githubusercontent.com/26230770/180946464-6adb1965-f6df-4193-877b-8b3b1f51f24f.png)

So I start apache2, mysql, elasticsearch, and redis-server services using the following command, but no luck. It shows the same above error:

`sudo service apache2 start && sudo service mysql start && sudo service elasticsearch start && sudo service redis-server start`

Please let me know how to overcome this issue. Thanks in anticipation.

**Comment by rangerz** [comment] 2022-07-27 18:32
I guess their service using the same ports, so try to `bin/stop` docker-magento and restart your service for your local project.

Error message needs to more details to confirm the cause of the issue.

Try to google the error message and fix the issue to share your result.

**Comment by markshust** [comment] 2022-12-04 14:50
Closing out as @rangerz's suggestion is valid 👍

**Closed by markshust** 2022-12-04 14:50 UTC
