### ISSUE TITLE
Compose file is invalid

### ISSUE THREAD

**Issue by yanpantoja** [markshust/docker-magento#800] opened 2022-10-27 21:58 UTC
**Description**

I'm getting the following error:

![Screenshot from 2022-10-27 18-56-20](https://user-images.githubusercontent.com/41760474/198405954-3296fca2-deff-4987-831a-4e1580aa107f.png)

Anyone faced this error before?

**Steps To Reproduce**
1. Followed the install instructions in readme.md

**Expected Result**

bin/download works

**Actual Result**

Error in bin/download

![Screenshot from 2022-10-27 19-01-14](https://user-images.githubusercontent.com/41760474/198406475-0886e250-e8fd-4b28-8a45-1f02cf673e2d.png)

**Comment by rangerz** [comment] 2022-10-28 01:07
lol, my bad...
https://docs.docker.com/compose/compose-file/#depends_on
Version 3 no longer supports the `condition` form of `depends_on`

Docker recommends this: https://docs.docker.com/compose/startup-order/

**Comment by rangerz** [comment] 2022-10-28 03:18
@yanpantoja What's your env ?
Linux or Mac, and the docker and docker-compose version.

**Comment by yanpantoja** [comment] 2022-10-28 03:32
Hi @rangerz 
Linux Ubuntu 20.04
Docker version 20.10.21
Docker Compose version v2.12.2

**Comment by rangerz** [comment] 2022-10-29 05:31
> Hi @rangerz Linux Ubuntu 20.04 Docker version 20.10.21 Docker Compose version v2.12.2

I used the same env. Could not reproduce this issue.
I guess `bin/docker-compose` to use `docker-compose` not `docker compose`

Please try to edit `bin/docker-compose`
```bash
if docker compose version 2> /dev/null; then
  DOCKER_COMPOSE="docker compose"
else
  DOCKER_COMPOSE="docker-compose"
fi
```

I have made a pull request to update this file.  https://github.com/markshust/docker-magento/pull/801

**Comment by markshust** [comment] 2022-11-02 10:26
Thanks @rangerz, made one suggestion, then I can merge this one in.

**Comment by markshust** [comment] 2022-11-20 15:29
Merged in 👍

**Closed by markshust** 2022-11-20 15:29 UTC
