### ISSUE TITLE
Unable to install Magento 2.4.3 via one line command

### ISSUE THREAD

**Issue by jsjsvsvs** [markshust/docker-magento#741] opened 2022-07-25 18:19 UTC
**Description**
I've tried installing Magento 2.4.3 with the one liner on two different laptops, but encountering an error.

**Steps To Reproduce**
1.  

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.3

**Expected Result**

completed magento 2.4.3 install

**Actual Result**

Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
124 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
[+] Running 7/7
 ⠿ Container local4-db-1             Stopped                                                                                                                                                                                           2.0s
 ⠿ Container vslocal4-elasticsearch-1  Stopped                                                                                                                                                                                           2.2s
 ⠿ Container vslocal4-app-1            Stopped                                                                                                                                                                                           1.5s
 ⠿ Container vslocal4-mailcatcher-1    Stopped                                                                                                                                                                                           1.4s
 ⠿ Container vslocal4-phpfpm-1         Stopped                                                                                                                                                                                           1.4s
 ⠿ Container vslocal4-redis-1          Stopped                                                                                                                                                                                           1.4s
 ⠿ Container vslocal4-rabbitmq-1       Stopped                                                                                                                                                                                           6.7s
[+] Running 7/7
 ⠿ Container vslocal4-rabbitmq-1       Started                                                                                                                                                                                           0.6s
 ⠿ Container vslocal4-redis-1          Started                                                                                                                                                                                           0.6s
 ⠿ Container vslocal4-elasticsearch-1  Started                                                                                                                                                                                           1.4s
 ⠿ Container vslocal4-app-1            Started                                                                                                                                                                                           1.4s
 ⠿ Container vslocal4-phpfpm-1         Started                                                                                                                                                                                           1.3s
 ⠿ Container vslocal4-mailcatcher-1    Started                                                                                                                                                                                           0.7s
 ⠿ Container vslocal4-db-1             Started                                                                                                                                                                                           0.8s
**chmod: cannot access 'bin/magento': No such file or directory**

**Comment by myselfhimself** [comment] 2022-07-25 21:15
This is a duplicate of #731 I recommend you try running a current PR patch for the onlinesetup script and bin/download set:

`curl -s https://raw.githubusercontent.com/markshust/docker-magento/6a2fb7e0cc3d959ce7d5a383a27197ba48687d62/lib/onelinesetup | bash -s -- magento.test 2.4.3`

your feedback will be appreciated

**Comment by myselfhimself** [comment] 2022-07-26 07:38
Sorry my advised command is wrong.. it will continue pulling the master branch's bin/install script instead of the pull request's one

**Comment by jsjsvsvs** [comment] 2022-07-26 15:33
Yes I am still getting the error

**Comment by myselfhimself** [comment] 2022-07-26 19:03
You may try manual steps at `https://github.com/markshust/docker-magento/issues/731#issuecomment-1195684708`
or in short work with a modified `bin/install` script like https://github.com/myselfhimself/docker-magento/blob/patch-1/compose/bin/download

Hopefully in 1-2 weeks the upstream docker-magento project will include the fix

**Comment by radub** [comment] 2022-12-02 07:12
@myselfhimself any news on the permanent fix?

> You may try manual steps at https://github.com/markshust/docker-magento/issues/731#issuecomment-1195684708
> or in short work with a modified bin/install script like https://github.com/myselfhimself/docker-magento/blob/patch-1/compose/bin/download
> 
> Hopefully in 1-2 weeks the upstream docker-magento project will include the fix

For this workaround to work it is required to replace all occurrences of docker-compose.yml with **compose.yaml** to prevent the following error:
```
sed: docker-compose.yml: No such file or directory
stat /Users/radub/Projects/m2-vanilla/docker-compose.yml: no such file or directory
Failed to start Docker services
```

**Comment by markshust** [comment] 2022-12-04 13:38
I'm going to close this out as 2.4.3 is EOL, and I have no plans to support EOL versions.

**Closed by markshust** 2022-12-04 13:38 UTC
