### ISSUE TITLE
One code setup can't access to bin/magento

### ISSUE THREAD

**Issue by NecmiGorkemKivanc** [markshust/docker-magento#769] opened 2022-09-08 06:48 UTC
**Description**
I tried setup magento 2.4.3-p1 version and i get this error when download the files:
bin/magento no such file  or directory

**Expected Result**
download magento's files

**Actual Result**
bin/magento no such file or directory

**Comment by shinesoftware** [comment] 2022-09-09 08:52
I can confirm what @NecmiGorkemKivanc has found!
I have downloaded the version 2.4.2 and I get the same problem issue.
Seems that the Magento is not downloaded correctly.

@markshust Could you please help us?

thanks

**Comment by NecmiGorkemKivanc** [comment] 2022-09-09 09:08
Hey @shinesoftware, if you need fastly resolve you can try to manual setup. It's worked for me.(Installed already exist project)

**Comment by shinesoftware** [comment] 2022-09-09 09:10
Hi @NecmiGorkemKivanc, yes thanks! 
I am trying to setup it manually but I'd like to improve this tool!
I'd like to use it for my new / old Magento project.

**Comment by jsjsvsvs** [comment] 2022-09-20 21:05
This issue is still happening, has anybody written a fix for it yet?

**Comment by shinesoftware** [comment] 2022-09-21 07:29
@jsjsvsvs I thing that we need a little help from @markshust

**Comment by jsjsvsvs** [comment] 2022-10-12 00:50
@NecmiGorkemKivanc  Which manual setup are you referring too? Manual Step > New Projects fails as well with bin/magento command not found. Same issue

**Comment by tangar76** [comment] 2022-10-18 12:11
I have the same issue when try to setup Magento 2.4.3-p3 with manual instructions during `bin/setup` command:
```
chmod: cannot access 'bin/magento': No such file or directory
```

**Comment by markshust** [comment] 2022-10-24 17:20
I'm willing to take in a PR that fixes this, but given that 2.3 reached EOL in September, and 2.4.3 reaches EOL in a little over a month, I have little motivation to fix these versions.

**Comment by markshust** [comment] 2022-10-24 17:21
I tagged this with a "help wanted" flag. If there isn't a corresponding PR to fix this by Nov 28 (EOL noted at https://experienceleague.adobe.com/docs/commerce-operations/release/planning/lifecycle-policy.html), I'll automatically close out this ticket as "will not fix".

**Comment by dupski** [comment] 2022-11-25 16:07
> I have the same issue when try to setup Magento 2.4.3-p3 with manual instructions during `bin/setup` command:
> 
> ```
> chmod: cannot access 'bin/magento': No such file or directory
> ```
> 
> UPD: but when try to install 2.4.5 or 2.4.5-p1 all work smoothly.

v2.4.4 and v2.4.5-p1 both broken for me using the one-line setup script (brand new user of this project) so it doesn't seem to be just old versions that have this problem

**Comment by markshust** [comment] 2022-11-27 17:29
2.4.3 is official end-of-life tomorrow (aka DEAD) so I won't be supporting it anymore, and will be proactively closing out this ticket as wontfix.

I just installed 2.4.5-p1 and the install went fine, so if you are having issues please open another ticket with full details (operating system, Docker version, exactly steps you are doing, etc.) and I'll check it out 👍

**Closed by markshust** 2022-11-27 17:29 UTC
Labels: help wanted

**Comment by jasonhildebrand** [comment] 2023-11-10 19:46
I struggled with this chmod error trying to install an older version (2.4.3-p3) for working with a legacy project.
The issue was that magento includes some composer plugins that need to be enabled, but the `composer create-project` command is called using `bin/clinotty` which is non-interactive.  Because of this composer assumes there is no permissions to enable the plugin, and the install does not complete successfully (but there is no apparent error).

The solution is to edit `bin/download` and change the relevant line (depending on edition you are installing) from `bin/clinotty` to `bin/cli`.

Then answer questions like this with `y`
    
    Do you trust "magento/magento-composer-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
