### ISSUE TITLE
autoload error

### ISSUE THREAD

**Issue by stanleyyylau** [markshust/docker-magento#175] opened 2019-08-15 15:09 UTC
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for amzn/amazon-pay-and-login-with-amazon-core-module 2.1.0 -> satisfiable by amzn/amazon-pay-and-login-with-amazon-core-module[2.1.0].
    - amzn/amazon-pay-and-login-with-amazon-core-module 2.1.0 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 2
    - Installation request for amzn/amazon-pay-module 2.1.0 -> satisfiable by amzn/amazon-pay-module[2.1.0].
    - amzn/amazon-pay-module 2.1.0 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 3
    - Installation request for amzn/login-with-amazon-module 2.1.0 -> satisfiable by amzn/login-with-amazon-module[2.1.0].
    - amzn/login-with-amazon-module 2.1.0 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 4
    - Installation request for colinmollenhour/php-redis-session-abstract v1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - colinmollenhour/php-redis-session-abstract v1.3.4 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 5
    - Installation request for klarna/module-core 4.4.5 -> satisfiable by klarna/module-core[4.4.5].
    - klarna/module-core 4.4.5 requires php ^5.6|~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 6
    - Installation request for klarna/module-kp 5.4.4 -> satisfiable by klarna/module-kp[5.4.4].
    - klarna/module-kp 5.4.4 requires php ^5.6|~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 7
    - Installation request for klarna/module-ordermanagement 4.3.4 -> satisfiable by klarna/module-ordermanagement[4.3.4].
    - klarna/module-ordermanagement 4.3.4 requires php ^5.6|~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 8
    - Installation request for magento/composer 1.2.0 -> satisfiable by magento/composer[1.2.0].
    - magento/composer 1.2.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 9
    - Installation request for magento/framework 101.0.6 -> satisfiable by magento/framework[101.0.6].
    - magento/framework 101.0.6 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
  Problem 10
    - Installation request for magento/magento2-base 2.2.6 -> satisfiable by magento/magento2-base[2.2.6].
    - magento/magento2-base 2.2.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 11
    - Installation request for magento/module-admin-notification 100.2.4 -> satisfiable by magento/module-admin-notification[100.2.4].
    - magento/module-admin-notification 100.2.4 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 12
    - Installation request for magento/module-advanced-pricing-import-export 100.2.4 -> satisfiable by magento/module-advanced-pricing-import-export[100.2.4].
    - magento/module-advanced-pricing-import-export 100.2.4 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 13
    - Installation request for magento/module-analytics 100.2.3 -> satisfiable by magento/module-analytics[100.2.3].
    - magento/module-analytics 100.2.3 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.20) does not satisfy that requirement.
  Problem 14
    - Installation request for magento

**Comment by markshust** [comment] 2019-08-15 18:40
Need more info (when it's happening, steps to replicate, etc.). I can't reproduce any issue, so closing this for now until the ticket is updated. Thanks

**Closed by markshust** 2019-08-15 18:40 UTC

**Comment by bencorlett** [comment] 2019-12-18 23:14
@stanleyyylau @markshust (or anybody else trawling this thread) I have also experienced this.

## Problem 

The issue is reproducible by running:

```bash
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- my host.test 2.1.18
```

The [PHP container is using PHP 7.3](https://github.com/markshust/docker-magento/blob/master/compose/magento-2/docker-compose.yml#L21) on the `master` branch which is incompatible with Magento 2.1, mainly due to [`mcrypt` no longer existing in PHP 7.2+](https://www.php.net/manual/en/intro.mcrypt.php).

## Solution

The solution is just to switch to an older one of @markshust's PHP images by [modifying your `docker-composer.yml`](https://github.com/markshust/docker-magento/blob/3e9d3774dbb8ee245101b925c45cdbf1e798ba7a/compose/magento-2/docker-compose.yml#L21):

```diff
   phpfpm:
-    image: markoshust/magento-php:7.3-fpm-1
+    image: markoshust/magento-php:7.0-fpm-9
     links:
```
