### ISSUE TITLE
Random 502 Bad Gateway error

### ISSUE THREAD

**Issue by esequielp** [markshust/docker-magento#1085] opened 2024-03-08 18:11 UTC
**Description**

I am using the last installation : 

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.6-p4 community

Error happens when go to especify product

![image](https://github.com/markshust/docker-magento/assets/22037850/a3f60884-add9-4941-9355-1dba3f3358fb)

![image](https://github.com/markshust/docker-magento/assets/22037850/433f651d-8c9e-4efb-8215-ffd0fc6493c1)

**Steps To Reproduce**
1. go to , https://magento.test/women/tops-women.html , then choose a especify product

**Expected Result**

open the product

**Actual Result**
give 502 Bad Gateway

**Comment by esequielp** [comment] 2024-03-08 18:21
This is my SO

![image](https://github.com/markshust/docker-magento/assets/22037850/c15c8db6-5cd5-4e2d-b18e-6045d761b245)

**Comment by YevhenZvieriev** [comment] 2024-03-14 15:57
Hi, @esequielp  

Did you change Nginx conf?
You should check the log files.

**Comment by esequielp** [comment] 2024-03-14 16:37
NO , I didnt change the nginx config, where I can see the logs files?

**Comment by YevhenZvieriev** [comment] 2024-03-14 17:08
To see the log files you can execute the `bin/log` script.

I hope you executed the `bin/magento setup:upgrade` command after deploying Magento sample data.

To be sure  try to execute these commands:

```
bin/fixowns
bin/fixperms
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy
bin/magento cache:flush
```

**Comment by giangvdm** [comment] 2024-03-16 08:56
I also encounter this 502 error when randomly refresh the page while having Xdebug enabled.

Logs from Nginx says: `recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.24.0.1, server: , request: "GET /customer/account/login/referer/aHR0cHM6Ly95b3VibG9iLmxvY2FsLw~~/ HTTP/2.0", upstream: "fastcgi://unix:/sock/docker.sock:", host: "youblob.local", referrer: "https://my.domain/"`

If Xdebug is disabled, no error occurs.

**Comment by YevhenZvieriev** [comment] 2024-03-16 09:46
Hi, @esequielp 

I understand your problem. I see, you have enabled `Xdebug helper`

Try to disable this, and tell me if it resolves your issue.

![Screenshot from 2024-03-16 11-43-23](https://github.com/markshust/docker-magento/assets/43544955/9a58ac8f-0f38-432d-80c6-4f199199bc58)

**Comment by derekBaldwinGG** [comment] 2024-03-22 22:32
When I enable xdebug, sometimes it works, sometimes it throws the 502 error. I can set breakpoints and it breaks as expected when it works, but half the time it throws a 502.

Here is my app log error:
`2024/03/22 22:25:18 [info] 30#30: *81 client 127.0.0.1 closed keepalive connection
2024/03/22 22:25:32 [error] 30#30: *55 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.228.1, server: , request: "POST /company/account/createPost/ HTTP/2.0", upstream: "fastcgi://unix:/sock/docker.sock:", host: "magento.test", referrer: "https://magento.test/company/account/create/"`

Here is my phpfpm related error:
`child 64 exited on signal 11 (SIGSEGV)`

Any ideas? I'm not a server admin. I used this docker-magento setup on older macs and it works fine.

**Comment by madmytrych** [comment] 2024-03-29 10:46
I often get 502 error when xdebug is enabled too.
There are logs:
```
2024-03-29 12:43:45 [29-Mar-2024 10:43:45] WARNING: [pool www] child 58 said into stderr: "Fri Mar 29 10:43:45 2024 (58): [Error] APM: Locking APM for 300 seconds for reason: Cannot connect to the agent"
2024-03-29 12:43:45 [29-Mar-2024 10:43:45] WARNING: [pool www] child 59 said into stderr: "Fri Mar 29 10:43:45 2024 (59): [Error] APM: Locking APM for 300 seconds for reason: Cannot connect to the agent"
2024-03-29 12:43:45 [29-Mar-2024 10:43:45] WARNING: [pool www] child 56 exited on signal 11 (SIGSEGV) after 5.021329 seconds from start
2024-03-29 12:43:45 [29-Mar-2024 10:43:45] NOTICE: [pool www] child 61 started
2024-03-29 12:43:46 - -  29/Mar/2024:10:43:46 +0000 "GET /index.php" 200
2024-03-29 12:43:46 [29-Mar-2024 10:43:46] WARNING: [pool www] child 60 said into stderr: "Fri Mar 29 10:43:46 2024 (60): [Error] APM: Locking APM for 300 seconds for reason: Cannot connect to the agent"
2024-03-29 12:44:04 [29-Mar-2024 10:44:04] WARNING: [pool www] child 57 exited on signal 11 (SIGSEGV) after 23.507697 seconds from start
2024-03-29 12:44:04 [29-Mar-2024 10:44:04] NOTICE: [pool www] child 62 started
```

**Comment by CarlosM-ESP** [comment] 2024-04-04 13:59
Cannot use the modified xdebug downgrade. found this error
`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.27. in /var/www/html/vendor/composer/platform_check.php on line 24`

**Comment by CarlosM-ESP** [comment] 2024-04-11 10:04
@markshust 
Good Morning, Mark. Does the new release of docker-magento for M2.4.7 corrects this issue?
Regards.

**Comment by markshust** [comment] 2024-04-12 23:09
@CarlosM-ESP I did regress the Composer version in the latest PHP <=8.2 images to the officially supported version, which may fix this issue.

**Comment by markshust** [comment] 2024-04-12 23:25
@CarlosM-ESP I'm looking into this further. I'm thinking the SPX extension that was added in a couple months ago could potentially be conflicting with Xdebug.

Also... https://bugs.xdebug.org/view.php?id=2253

I'm wondering if we should downgrade to the last major version release of Xdebug (3.2.2).

**Comment by markshust** [comment] 2024-04-12 23:31
I've replicated the issue, and have confirmed that the Xdebug is causing it.

**Comment by markshust** [comment] 2024-04-13 03:09
I have confirmed that a "502 Bad Gateway" error is always returned and replicable whenever Xdebug 3.3.1 is enabled (per bug filed at https://bugs.xdebug.org/view.php?id=2253).

The issue is resolved by downgrading Xdebug back to 3.2.2. While this works for PHP 8.1/8.2, unfortunately it is not an option when running PHP 8.3 due to package version constraints (pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 8.3.6).

I'll update the PHP 8.1/8.2 images to downgrade Xdebug back to 3.2.2. I'll have this updated tomorrow.

Unfortunately, there is no resolution for PHP 8.3 due to hard version constraints set by Xdebug.

I'm surprised others aren't commenting on the Xdebug bug/issue as running Xdebug on PHP 8.3 is currently not an option. If you'd like this fixed for PHP 8.3, I'd recommend to comment on the ticket at https://bugs.xdebug.org/view.php?id=2253 to increase the likelihood of this bug getting resolved.

**Comment by markshust** [comment] 2024-04-13 03:20
Another possibly related bug before I build & tag new images, related to running Blackfire and Xdebug at the same time: https://bugs.xdebug.org/view.php?id=2230

Few possible resolutions/options:
1. It may be possible to circumvent this issue, as noted, by ensuring Blackfire is loaded before Xdebug. I'm not entirely sure how to do this.
2. A fix for this has already been merged into 3.3dev, but it's not yet released: https://bugs.xdebug.org/changelog_page.php. I'm not sure if we can monkey-patch this diff on top of 3.3.1, or if there is a way to install the 3.3dev version with pecl.
3. I haven't confirmed this is the issue yet, but if it is, we could also simply disable Blackfire by default.

**Comment by markshust** [comment] 2024-04-13 03:28
FYI I don't think changing the load order of extensions is possible, as the ini files are loaded alphabetically, and it seems as though blackfire is already loading before xdebug:

<img width="1754" alt="Screenshot 2024-04-12 at 11 25 16 PM" src="https://github.com/markshust/docker-magento/assets/437029/03e8a52f-ef96-4eb3-b01c-f8621216c671">

But this is not representative of the output, as it looks like it is loading after xdebug:
```
app@cc351baed70e:/usr/local/lib/php$ php -v
PHP 8.2.18 (cli) (built: Apr 11 2024 19:28:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.18, Copyright (c), by Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
    with blackfire v1.92.13~linux-x64-non_zts82, https://blackfire.io, by Blackfire
```

If the output is unrelated, this means that Blackfire is probably loading first, and that issue or possible fix is not applicable. It's getting late here, but I'll look more into this tomorrow.

**Comment by esequielp** [comment] 2024-04-13 14:39
Thanks @markshust Please inform when you resolve this issue!

**Comment by markshust** [comment] 2024-04-13 15:38
I've confirmed that [this issue of Xdebug conflicting with the Blackfire extension](https://bugs.xdebug.org/view.php?id=2230) is the most likely culprit of this bug, as Xdebug 3.3.1 works with PHP 8.3 if the Blackfire extension is disabled. 

Here's how I'll proceed:
1. Revert PHP 8.1 and 8.2 images to use Xdebug 3.2.2, as both Xdebug and Blackfire work at the same time on this version.
2. Since PHP 8.3 requires Xdebug 3.3 or higher, we will keep Xdebug at 3.3.1, but disable Blackfire by default, as it's not nearly as widely used as Xdebug.
3. Because of #2, I created a new `bin/blackfire` script to easily enable or disable Blackfire (https://github.com/markshust/docker-magento/pull/1115). This will allow those who wish to use Blackfire to easily enable it on PHP 8.3, but note that until the above Xdebug bug is resolved, you cannot run Xdebug at the same time as Blackfire. I'll add this to the README as a "known issue".

The code is about ready to go, but I will need GitHub actions to recompile the new images. This process typically takes about 90 minutes once it starts, so I'll check back later to update the compose.yaml file to the new image version once it's complete, and tag this update as 46.1.0.

This version will also contain the PHP Swoole extension for Adobe Commerce GraphQL Application Layer support (https://github.com/markshust/docker-magento/pull/1114). I haven't delved into this topic yet to find out how to configure it with Commerce or run the application layer, but we'll need this extension anyways for this app layer, so I figured I'd build this in since we'll need new images anyways (I forgot to add it in the initial PHP 8.3 image at the time of the Magento 2.4.7 release earlier this week).

I'll update this ticket as soon as the new images and configuration has been published.

**Closed** 2024-04-13 15:57 UTC
Labels: confirmed

**Comment by markshust** [comment] 2024-04-13 16:00
It looks like GitHub auto-closed this ticket, but it should be resolved.

The images are being re-built right now (https://github.com/markshust/docker-magento/actions). I'll tag docker-magento `46.1.0` when they have completed building.

**Comment by markshust** [comment] 2024-04-13 17:57
This issue should now be resolved, as docker-magento 46.1.0 has been released (https://github.com/markshust/docker-magento/pull/1119).

I created a subsequent ticket about Xdebug 3.3 and Blackfire incompatibility at https://github.com/markshust/docker-magento/issues/1118 which you can watch for future updates.

**Comment by CarlosM-ESP** [comment] 2024-04-14 13:26
@markshust
Thank you Mark for your dedication!

**Comment by CarlosM-ESP** [comment] 2024-04-15 09:15
Magento 2.4.7 installed. Xdebug problem disappeared. Thank you, Mark!

**Comment by nellodb** [comment] 2024-05-20 15:57
Thanks for the update. 
I'm on a MacOS Intel and I was experiencing the random 502s aswell, ran a `bin/update` which brought the docker's phpfpm to `8.3-fpm-2`. 
The random 502s were fixed but even though I had disabled blackfire and enabled XDebug the environment pretty much ran to a halt with `php-fpm` constantly maxed-out at a hundred percentage and a huge CPU load. 

I've downgraded to 
```phpfpm:
    image: markoshust/magento-php:8.2-fpm-4
```

which at the moment seems to run just fine. Not sure where the issue lies, just commented out of curiosity to check if anyone ran into the same issue.
